name: loomi_ui_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  flutter_svg: 2.0.8
  cached_network_image: 3.3.0

  camera: 0.10.5+5
  image: 4.1.3
  path_provider: 2.1.1
  video_player: 2.7.2
  subtitle_wrapper_package: 2.2.0
  wakelock_plus: 1.1.3
  file_picker: 6.0.0
  mobx: 2.3.0+1
  flutter_mobx: 2.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/vectors/
